<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="TestVagrantSuite" duration-ms="85180" started-at="2021-07-16T06:35:44Z" finished-at="2021-07-16T06:37:09Z">
    <groups>
    </groups>
    <test name="TestVagrantTests" duration-ms="85180" started-at="2021-07-16T06:35:44Z" finished-at="2021-07-16T06:37:09Z">
      <class name="com.TestVagrant.Tests.TestVagrantTest">
        <test-method status="FAIL" signature="testVagrantTestCase()[pri:0, instance:com.TestVagrant.Tests.TestVagrantTest@69ea3742]" name="testVagrantTestCase" duration-ms="83108" started-at="2021-07-16T06:35:44Z" finished-at="2021-07-16T06:37:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Since some Weather parameters did not match the test is failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Since some Weather parameters did not match the test is failed
at org.testng.Assert.fail(Assert.java:96)
at com.TestVagrant.Util.PerformWeatherDataComparison.compare(PerformWeatherDataComparison.java:75)
at com.TestVagrant.Tests.TestVagrantTest.testVagrantTestCase(TestVagrantTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVagrantTestCase -->
        <test-method status="PASS" signature="shutDown()[pri:0, instance:com.TestVagrant.Tests.TestVagrantTest@69ea3742]" name="shutDown" is-config="true" duration-ms="1645" started-at="2021-07-16T06:37:07Z" finished-at="2021-07-16T06:37:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutDown -->
      </class> <!-- com.TestVagrant.Tests.TestVagrantTest -->
    </test> <!-- TestVagrantTests -->
  </suite> <!-- TestVagrantSuite -->
</testng-results>
